name: pwmini2022_v9
description: Homework Manager
version: 9.2.3
homepage: https://github.com/jamesbmadden/pwmini2022
author: James Madden

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.12.0
  firebase: ^5.0.0
  intl: ^0.15.7

dev_dependencies:
  build_runner: ^1.2.0
  build_test: ^0.10.2
  build_web_compilers: ^1.1.0
  sass_builder: ^2.0.0
